server:
  port: 1111
eureka:
  instance:
    hostname: localhost
spring:
  application:
     name: APIGATWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: ADMIN-SERVICE
        uri: http://localhost:8086/
        predicates:
        - Path=/api/admins/**
        
      - id: USER-SERVICE
        uri: http://localhost:8080/
        predicates:
        - Path=/api/users/**
        
      - id: ORDER-SERVICE
        uri: http://localhost:8084/
        predicates:
        - Path=/api/order/**
        
      - id: PRODUCT-SERVICE
        uri: http://localhost:8082/
        predicates:
        - Path=/api/products/**
        

        

